### PR TITLE
Hotfix save null as integer

### PR DESCRIPTION
**Pull request by zonky2**
Hotfix save null (0) as "integer string"

### CODE REVIEW

**Comment by zonky2** [comment]
Comment updated

**Comment by richardhj** [comment]
The zero will not be saved as an integer. The zero will be represented by a string. An integer zero would get lost too with this if-condition.
Maybe we should use an identical check (`===` instead of `==`) or use the function `strlen()`.
Comment could be "Skip empty cols but preserve cols containing '0'".

**Comment by zonky2** [comment]
I mean as "integer string"

**Comment by richardhj** [comment]
I know 😇

**Comment by baumannsven** [comment]
Merged in 790915bb265d5182e69c7de8eaf6e3ccd69433dd

**Pull request closed without merging**
